# Permalinks
permalink:           pretty

# Setup
title:               Stephanie Auer
tagline:             A Data Science Blog
url:                 http://sauer3.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Stephanie Auer
  url:               https://twitter.com/stephanie_auer
  email:             stephanie.auer@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/sauer3

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
